[versions]
kotlin = "2.0.0"
compose = "1.6.11"
javagi = "0.10.1"

[libraries]
javagi-gtk = { group = "io.github.jwharm.javagi", name = "gtk", version.ref = "javagi" }
javagi-adw = { group = "io.github.jwharm.javagi", name = "adw", version.ref = "javagi" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }